spring:
  application:
    name: test
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
server:
  port: 8080
mybatis-plus:
  check-config-location: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    cache-enabled: false
    default-fetch-size: 5000
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: cn.com.zls.entity
